services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
  
  TRAW\PowermailJiraIssues\:
    resource: '../Classes/*'

  TRAW\PowermailJiraIssues\EventListener\PowermailSubmitEventListener:
    tags:
      - name: event.listener
        identifier: 'traw/powermail-jira-submit'
        method: pushToJira

  TRAW\PowermailJiraIssues\Domain\Model\Form:
    tags:
      - name: 'extender.extends'
        class: In2code\Powermail\Domain\Model\Form